---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - image.fluxcd.io
  resources:
  - imagerepositories
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.fluxcd.io
  resources:
  - imagerepositories/status
  verbs:
  - get
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - alerts
  - providers
  - receivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - receivers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.fluxcd.io
  resources:
  - buckets
  - gitrepositories
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.fluxcd.io
  resources:
  - buckets/status
  - gitrepositories/status
  - helmrepositories/status
  - ocirepositories/status
  verbs:
  - get
